[package]
name = "project1"
version = "0.1.0"
edition = "2021"

# Dependencies
[dependencies]
ic-cdk = "0.6.1"
ic-cdk-macros = "0.6.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"     # Path to the renamed lib.rs file
